### PR TITLE
Forms & Collapsed Sidebar

### PR DESCRIPTION
**Pull request by janicez11**
Issues: 
#120 
#121 
#124  (border or no border on the right of the mini sidebar?)

### CODE REVIEW

**Comment by kevinlee12** [comment]
@janicez11, looks great, did spot a little :bug: in the students area:

image

**Comment by kevinlee12** [comment]
@janicez11 as for the border, no border, i think it would be best with a border :smile:

**Comment by janicez11** [comment]
as for the bug, It looks fine from my side 

screen shot 2015-08-08 at 11 10 34 pm
screen shot 2015-08-08 at 11 10 42 pm

**Comment by kevinlee12** [comment]
will merge in, but will file a bug and resolve later.

**Pull request merged**
